---
# Install k3s standalone server 

- name: Download remote k3s installer
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s.sh

- name: Run Downloaded k3s installer
  shell: 
    cmd: cat /tmp/k3s.sh | sudo bash -
    creates: /etc/systemd/system/k3s.service

- name: Set file permissions of /etc/rancher/k3s
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'
