galaxy_info:
  role_name: p10k
  author: diodonfrost
  description: Ansible role for install powerlevel10k
  license: license Apache-2.0
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - buster
        - stretch
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial
    - name: Amazon
      versions:
        - 2017.12
    - name: opensuse
      versions:
        - 15.2
        - 15.1
        - 15.0
    - name: ArchLinux
      versions:
        - any
    - name: MacOSX
      versions:
        - all
    - name: FreeBSD
      versions:
        - 11.2
        - 10.4
        - 10.3
    - name: OpenBSD
      versions:
        - 6.0
        - 6.4

  galaxy_tags:
    - zsh
    - shell
    - system
    - git

dependencies: []
